# Trakx YAML config
# All times are measured in seconds
# Set timers to 0 for off

trakx:
  prod: true
  index: "index.html"
  expvar:
    enabled: true
    every: 1
    port: 1338

tracker:
  http:
    enabled: false
    port: 1337 # also serves the index

  udp:
    enabled: true
    port: 1337
    checkconnid: true

  numwant:
    default: 75
    max: 400

  # message for stopping clients
  stoppedmsg: "See you space cowboy..."

  # time between metrics generation
  metrics: 1800
  
  # Announce interval for clients
  announce: 1200

# Databases are in ~/.trakx/
database:
  peer:
    filename: "peers.db"
    trim: 300
    write: 300
    timeout: 2800
  conn:
    filename: "conn.db"
    trim: 300
    timeout: 86400 # 24h
