# Trakx YAML config
# All times are measured in seconds
# Set timers to 0 for off

trakx:
  prod: true
  index: "index.html"

  # Expvar is served on /stats over http port
  expvar:
    every: 1

  pprof:
    port: 1338 # set to 0 to disable

  # nofile limit 0 for default
  # high value used here so that we can queue connections for processing
  # trakx will automatically drop connections based on read/write timeout seen below
  ulimit: 99999

tracker:
  http:
    enabled: true
    port: 1337 # also serves expvar, index, ect.
    readtimeout: 3
    writetimeout: 10
    qsize: 100000 # 100K = ~1.5mb
    accepters: 10
    threads: 2048

  udp:
    enabled: true
    port: 1337
    checkconnid: true
    threads: 1024

  numwant:
    default: 75
    max: 300

  # message for stopping clients
  stoppedmsg: "See you space cowboy..."
  
  # Announce interval for clients
  announce: 1800 # 30m

# Databases are in ~/.trakx/
database:
  peer:
    filename: "peers.db"
    trim: 600 # 10m
    write: 900 # 15m
    timeout: 2400 # 40m
  conn:
    filename: "conn.db"
    trim: 600 # 10m
    timeout: 1800 # 30m
