# Trakx YAML config

trakx:
  prod: true

tracker:
  index: "index.html"
  http: false # http tracker on/off
  checkconnid: true # whether trakx should check the udp connid
  ports: # 0 = off for ports
    udp: 1337
    http: 1337
    expvar: 1338
  numwant:
    default: 75
    max: 400
  # message for stopping clients
  stopped: "See you space cowboy..."
  # time between metrics generation (0 = off)
  metrics: 1800
  # Announce interval for clients
  announce: 1200

# Databases are in ~/.trakx/
database:
  peer:
    filename: "peers.db"
    trim: 300  # how often to trim in seconds
    write: 300 # write interval in seconds
    timeout: 2800 # peer timeout for trim
  conn:
    filename: "conn.db"
    trim: 300 # how often to trim in seconds
